# Generated by Django 2.0.2 on 2018-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
