# Generated by Django 2.0.2 on 2018-03-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_bloglistpage_blogmainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmainpage',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blogmainpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
