# Generated by Django 2.0.2 on 2018-03-17 15:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
        ('service', '0002_auto_20180317_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('feature_title', models.CharField(blank=True, max_length=255)),
                ('feature_intro', wagtail.core.fields.RichTextField(blank=True)),
                ('embed_url', models.URLField(blank=True, verbose_name='Embed URL')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MobileAppPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('mobile_app_name', models.CharField(blank=True, max_length=255)),
                ('mobile_app_intro', wagtail.core.fields.RichTextField(blank=True)),
                ('mobile_service_title', models.CharField(blank=True, max_length=255)),
                ('mobile_feature_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('service_title', models.CharField(blank=True, max_length=255)),
                ('service_intro', wagtail.core.fields.RichTextField(blank=True)),
                ('embed_url', models.URLField(blank=True, verbose_name='Embed URL')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_item', to='service.MobileAppPage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='featureitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_item', to='service.MobileAppPage'),
        ),
    ]
