# Generated by Django 2.0.2 on 2018-03-18 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('service', '0003_auto_20180317_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapppage',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
