# Generated by Django 2.0.2 on 2018-04-06 10:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_mobileapppage_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIndexItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading1', models.CharField(blank=True, max_length=255)),
                ('heading2', models.CharField(blank=True, max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_index_items', to='service.ServiceIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
