# Generated by Django 2.0.2 on 2018-04-06 12:35

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20180406_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepagesolutions',
            name='image',
        ),
        migrations.RemoveField(
            model_name='servicepagesolutions',
            name='page',
        ),
        migrations.RenameField(
            model_name='servicepagemobilityindustry',
            old_name='embed_url',
            new_name='embed_url1',
        ),
        migrations.RenameField(
            model_name='servicepagemobilityindustry',
            old_name='heading',
            new_name='heading1',
        ),
        migrations.RenameField(
            model_name='servicepagemobilityindustry',
            old_name='intro',
            new_name='heading1_intro',
        ),
        migrations.AddField(
            model_name='servicepagemobilityindustry',
            name='embed_url2',
            field=models.URLField(blank=True, verbose_name='Embed URL'),
        ),
        migrations.AddField(
            model_name='servicepagemobilityindustry',
            name='heading2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicepagemobilityindustry',
            name='heading2_intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepagemobilityindustry',
            name='url_title1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servicepagemobilityindustry',
            name='url_title2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='ServicePageSolutions',
        ),
    ]
