# Generated by Django 2.0.2 on 2018-04-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20180406_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='service_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
