# Generated by Django 2.0.2 on 2018-04-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20180407_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceindexpage',
            name='why_us',
            field=models.CharField(blank=True, default='Why us ?', max_length=255),
        ),
    ]
