# Generated by Django 2.0.2 on 2018-04-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_serviceindexpage_why_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='service_intro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
