# Generated by Django 2.0.2 on 2018-05-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_servicepagenav'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepagenav',
            name='embed_url',
            field=models.URLField(blank=True, verbose_name='Embed URL'),
        ),
    ]
