# Generated by Django 2.0.2 on 2018-05-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_servicepagenav_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceindexpage',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='service_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicepageitems',
            name='heading1_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicepageitems',
            name='heading2_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicepagemobilityindustry',
            name='heading1_intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicepagemobilityindustry',
            name='heading2_intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
