# Generated by Django 2.0.2 on 2018-05-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20180501_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='innerpagesubhead',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
