# Generated by Django 2.0.2 on 2018-03-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180310_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesectionimage',
            old_name='video_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='homepagesectionimage',
            name='white_paper_image',
        ),
    ]
