# Generated by Django 2.0.2 on 2018-03-10 14:25

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180310_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='company',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='message',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='phone',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
