# Generated by Django 2.0.2 on 2018-03-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180310_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='image',
            new_name='logo_image',
        ),
    ]
