# Generated by Django 2.0.2 on 2018-04-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180427_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeatureimage',
            name='embed_url',
            field=models.URLField(blank=True, verbose_name='Embed URL'),
        ),
        migrations.AddField(
            model_name='homepagegalleryimage',
            name='embed_url',
            field=models.URLField(blank=True, verbose_name='Embed URL'),
        ),
        migrations.AddField(
            model_name='homepagesectionblogimage',
            name='embed_url',
            field=models.URLField(blank=True, verbose_name='Embed URL'),
        ),
        migrations.AddField(
            model_name='homepagesectioncasestudyimage',
            name='embed_url',
            field=models.URLField(blank=True, verbose_name='Embed URL'),
        ),
        migrations.AddField(
            model_name='homepagesectionimage',
            name='embed_url',
            field=models.URLField(blank=True, verbose_name='Embed URL'),
        ),
    ]
