# Generated by Django 2.0.2 on 2018-04-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180428_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagegalleryimage',
            name='embed_url',
        ),
    ]
