# Generated by Django 2.0.2 on 2018-05-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180501_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='intro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
