# Generated by Django 2.0.2 on 2018-05-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerblock',
            name='block_intro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='careerworkculture',
            name='block_intro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companycareerspage',
            name='career_intro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
