# Generated by Django 2.0.2 on 2018-05-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20180501_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycareerspage',
            name='career_opening_url',
            field=models.URLField(blank=True, verbose_name='Embed URL'),
        ),
    ]
