# Generated by Django 2.0.2 on 2018-05-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companycareerspage_career_opening_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycareerspage',
            name='career_opening_url',
            field=models.URLField(blank=True, verbose_name='career_opening_url'),
        ),
    ]
