# Generated by Django 2.0.2 on 2018-05-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
