# Generated by Django 2.0.2 on 2018-03-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesindexpage',
            name='indexheading',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
