# Generated by Django 2.0.2 on 2018-03-18 14:23

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourcesindexpage_indexheading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcesfeaturedprojectspage',
            name='subheading',
        ),
        migrations.AddField(
            model_name='resourcesfeaturedprojectspage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
