# Generated by Django 2.0.2 on 2018-03-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20180318_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredprojectsgallary',
            old_name='block_title',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='featuredprojectsgallary',
            old_name='block_intro',
            new_name='subheading',
        ),
    ]
