# Generated by Django 2.0.2 on 2018-04-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20180318_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcesfeaturedprojectspage',
            name='resourcesNav1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resourcesfeaturedprojectspage',
            name='resourcesNav2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resourcesfeaturedprojectspage',
            name='resourcesNav3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resourcesfeaturedprojectspage',
            name='resourcesNav4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resourcesfeaturedprojectspage',
            name='intro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
