# Generated by Django 2.0.2 on 2018-05-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20180501_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcesindexpage',
            name='intro',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
